package pl.sdacademy.domain.shared;

public enum ApiStatus {
    DESCRIPTION_NOT_FOUND,
    INVALID_TASK_TOKEN,
    TASK_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    NO_MORE_TASKS,
    BAD_SUBMIT_TOKEN,
    MEDIA_TYPE_NOT_SUPPORTED,
    MESSAGE_NOT_READABLE,
    DEBUG_MODE_DISABLED,
    VALIDATION_ERROR,
    INVALID_ENDPOINT,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    VERIFICATION_NOT_FOUND,
    INVALID_VERIFICATION_CODE,
    INVALID_FILE_NAME,
    FILE_IS_EMPTY,
    IMAGE_NOT_FOUND,
    INVALID_MULTIPART_REQUEST,
    INVALID_METHOD_ARGUMENT_TYPE,
    FILE_IS_NOT_AN_IMAGE,
    USER_IS_NOT_VERIFIED,
    IMAGE_NOT_ACCESSIBLE
}
